import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
	return (
		<Head>
			<title>3D pootal</title>
			<meta name="description" content="Generated by one nerd" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	)
}

export default Home
